import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from core.models import RemediationStatus


class VerificationStatus(str, Enum):
    PASS    = "PASS"
    FAIL    = "FAIL"
    UNKNOWN = "UNKNOWN"     # LLM could not determine from outputs


@dataclass
class FileToFix:
    """
    Represents a single file that needs to be fixed.
    """
    path            : str
    line            : int        = 0
    function        : str        = ""
    exception       : str        = ""
    fix_description : str        = ""
    current_content : str        = ""

    @classmethod
    def from_monitoring(cls, entry: Dict) -> "FileToFix":
        return cls(
            path            = entry.get("file", entry.get("path", "")),
            line            = int(entry.get("line", 0)),
            function        = entry.get("function", ""),
            exception       = entry.get("exception", ""),
            fix_description = entry.get("fix_description", ""),
        )

    def __str__(self) -> str:
        return (
            f"FileToFix(path={self.path}, "
            f"line={self.line}, "
            f"function={self.function}(), "
            f"exception={self.exception})"
        )


@dataclass
class Solution:
    """
    Generated by the Knowledge Agent after RAG investigation.
    Passed to the Self-Healing Agent for execution.
    """
    incident_id        : str
    root_cause         : str
    healing_prompt     : str
    confidence         : float
    suggested_commands : List[str]       = field(default_factory=list)
    references         : List[str]       = field(default_factory=list)
    source             : str             = "knowledge_base"
    created_at         : datetime        = field(default_factory=datetime.utcnow)
    files_to_modify    : List[FileToFix] = field(default_factory=list)

    def __str__(self):
        return (
            f"Solution(incident={self.incident_id}, "
            f"confidence={self.confidence:.2f}, "
            f"source={self.source})"
        )


@dataclass
class LLMFixResponse:
    """Response from the LLM Fixer Agent after analyzing a Solution."""
    incident_id          : str
    modified_files       : List[Dict]
    steps                : List[str]
    confidence           : float
    remediation_commands : List[Dict]    = field(default_factory=list)
    raw_response         : Optional[str] = None
    created_at           : datetime      = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"LLMFixResponse(incident={self.incident_id}, "
            f"files={len(self.modified_files)}, "
            f"confidence={self.confidence:.2f})"
        )


@dataclass
class FileModificationResult:
    """Holds the before/after state of a single file touched by the fixer."""
    path        : str
    old_content : str
    new_content : str
    action      : str
    applied     : bool = False
    backup_path : Optional[str] = None
    error       : Optional[str] = None

    def __str__(self):
        status = "applied" if self.applied else ("error" if self.error else "pending")
        return (
            f"FileModificationResult("
            f"path={self.path}, "
            f"action={self.action}, "
            f"backup={self.backup_path}, "
            f"status={status})"
        )


@dataclass
class CommandExecutionResult:
    """Outcome of a single remediation command executed after file changes."""
    command     : str
    description : str
    order       : int
    on_failure  : str
    returncode  : Optional[int] = None
    stdout      : str = ""
    stderr      : str = ""
    skipped     : bool = False
    error       : Optional[str] = None

    @property
    def succeeded(self) -> bool:
        return self.returncode == 0

    def __str__(self):
        if self.skipped:
            state = "skipped"
        elif self.error:
            state = f"error({self.error})"
        elif self.returncode is None:
            state = "pending"
        else:
            state = "ok" if self.succeeded else f"failed(rc={self.returncode})"
        return (
            f"CommandExecutionResult("
            f"order={self.order}, "
            f"cmd={self.command!r}, "
            f"state={state})"
        )


@dataclass
class CommandResult:
    """Result of a single verification command execution."""
    command   : str
    exit_code : int
    stdout    : str
    stderr    : str
    passed    : bool
    error     : Optional[str] = None

    def __str__(self):
        status = "✓" if self.passed else "✗"
        return (
            f"CommandResult({status} exit={self.exit_code}, "
            f"cmd={self.command[:60]})"
        )


@dataclass
class VerificationReport:
    """Final report produced by the LLM Verifier."""
    incident_id  : str
    status       : VerificationStatus
    commands_run : List[str]
    results      : List[CommandResult]
    reason       : str
    confidence   : float
    raw_response : Optional[str] = None
    created_at   : datetime      = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"VerificationReport("
            f"incident={self.incident_id}, "
            f"status={self.status.value}, "
            f"commands={len(self.commands_run)}, "
            f"confidence={self.confidence:.2f})"
        )


@dataclass
class SelfHealingResult:
    """
    Final result returned by the Self-Healing Agent after processing a Solution.

    NEW FIELDS:
        instructions : Human-readable numbered steps for INSTRUCTIONS_ONLY results
                       (when there are no files to fix automatically).
        retry_count  : How many times the self-healing loop has retried this incident.
    """
    incident_id                 : str
    status                      : RemediationStatus
    file_modifications          : List[FileModificationResult]  = field(default_factory=list)
    steps                       : List[str]                     = field(default_factory=list)
    confidence                  : float                         = 0.0
    validation_errors           : List[str]                     = field(default_factory=list)
    remediation_command_results : List[CommandExecutionResult]  = field(default_factory=list)
    llm_response                : Optional[LLMFixResponse]      = None
    verification                : Optional[VerificationReport]  = None
    # ── NEW ──────────────────────────────────────────────────────────────────
    instructions                : str                           = ""
    retry_count                 : int                           = 0
    created_at                  : datetime                      = field(default_factory=datetime.utcnow)

    def __str__(self):
        ver     = self.verification.status.value if self.verification else "not_run"
        cmd_ok  = sum(1 for c in self.remediation_command_results if c.succeeded)
        cmd_tot = len(self.remediation_command_results)
        return (
            f"SelfHealingResult("
            f"incident={self.incident_id}, "
            f"status={self.status.value}, "
            f"files={len(self.file_modifications)}, "
            f"cmds={cmd_ok}/{cmd_tot}, "
            f"verification={ver}, "
            f"confidence={self.confidence:.2f}, "
            f"retry={self.retry_count})"
        )