"""
shared/models.py
----------------
Shared dataclasses for the Scaffold Agent.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Optional
from uuid import uuid4


class Language(str, Enum):
    PYTHON  = "python"
    NODE    = "node"
    JAVA    = "java"
    GO      = "go"
    RUST    = "rust"
    UNKNOWN = "unknown"


class Framework(str, Enum):
    FASTAPI  = "fastapi"
    DJANGO   = "django"
    FLASK    = "flask"
    EXPRESS  = "express"
    NEXTJS   = "nextjs"
    NUXT     = "nuxt"
    REACT    = "react"
    VUE      = "vue"
    ANGULAR  = "angular"
    SVELTE   = "svelte"
    SPRING   = "spring"
    GIN      = "gin"
    UNKNOWN  = "unknown"


class ProjectSize(str, Enum):
    SMALL      = "small"       # Dockerfile + docker-compose only
    MEDIUM     = "medium"      # + GitHub Actions
    PRODUCTION = "production"  # + Kubernetes


class DeployTarget(str, Enum):
    DOCKER     = "docker"
    KUBERNETES = "kubernetes"


class CicdPlatform(str, Enum):
    GITHUB = "github"
    NONE   = "none"


@dataclass
class DeployConfig:
    """
    Auto-detected deployment configuration from project structure.
    No user input needed — scanner fills this in.
    """
    project_size  : ProjectSize  = ProjectSize.SMALL
    deploy_target : DeployTarget = DeployTarget.DOCKER
    cicd_platform : CicdPlatform = CicdPlatform.GITHUB
    has_database  : bool         = False
    database_type : str          = "none"   # postgres / mongo / mysql / redis / none


@dataclass
class ProjectContext:
    """
    Built by project_scanner.py — full picture of the project.
    Passed to the LLM for analysis and file generation.
    """
    project_path   : str
    language       : Language         = Language.UNKNOWN
    framework      : Framework        = Framework.UNKNOWN
    entry_point    : str              = ""
    port           : int              = 8000
    dependencies   : list[str]        = field(default_factory=list)
    files_snapshot : dict[str, str]   = field(default_factory=dict)
    deploy_config  : DeployConfig     = field(default_factory=DeployConfig)
    scanned_at     : datetime         = field(default_factory=datetime.now)

    @property
    def project_name(self) -> str:
        """Returns kebab-case project name from folder name."""
        return Path(self.project_path).name.lower().replace(" ", "-").replace("_", "-")


@dataclass
class GeneratedFile:
    """A single file generated by the LLM."""
    filename    : str
    content     : str
    description : str = ""


@dataclass
class ScaffoldResult:
    """
    Final output of scaffold_agent.py.
    Contains all generated files ready to be written to disk.
    """
    id              : str                    = field(default_factory=lambda: str(uuid4()))
    project_path    : str                    = ""
    language        : Language               = Language.UNKNOWN
    framework       : Framework              = Framework.UNKNOWN
    generated_files : list[GeneratedFile]    = field(default_factory=list)
    created_at      : datetime               = field(default_factory=datetime.now)
    success         : bool                   = True
    error           : Optional[str]          = None

    def summary(self) -> str:
        files = [f.filename for f in self.generated_files]
        return f"Generated {len(files)} files: {', '.join(files)}"