"""
core/models.py
--------------
Core data models used across all agents in the system.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


# ============================================================
# Enums
# ============================================================

class Severity(str, Enum):
    LOW      = "low"
    MEDIUM   = "medium"
    HIGH     = "high"
    CRITICAL = "critical"


class IncidentStatus(str, Enum):
    OPEN          = "open"
    INVESTIGATING = "investigating"
    REMEDIATING   = "remediating"
    RESOLVED      = "resolved"
    FAILED        = "failed"


class AgentStatus(str, Enum):
    IDLE    = "idle"
    RUNNING = "running"
    STOPPED = "stopped"
    ERROR   = "error"


class DeploymentStatus(str, Enum):
    PENDING     = "pending"
    RUNNING     = "running"
    SUCCESS     = "success"
    FAILED      = "failed"
    ROLLED_BACK = "rolled_back"


class RemediationStatus(str, Enum):
    PENDING           = "pending"
    APPROVED          = "approved"
    RUNNING           = "running"
    SUCCESS           = "success"
    FAILED            = "failed"
    REJECTED          = "rejected"
    # ── NEW ──────────────────────────────────────────────────────────────
    INSTRUCTIONS_ONLY = "instructions_only"   # No files to fix — human action required
    ROLLED_BACK       = "rolled_back"          # Fix applied but verification failed → reverted


# ============================================================
# Core Models
# ============================================================

@dataclass
class Metric:
    """A single metric reading from the Monitoring Agent."""
    name: str
    value: float
    unit: str
    service: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    labels: Dict[str, str] = field(default_factory=dict)

    def __str__(self):
        return f"Metric({self.name}={self.value}{self.unit}, service={self.service})"


@dataclass
class Log:
    """A single log entry from the Monitoring Agent."""
    message: str
    level: str
    service: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self):
        return f"Log({self.level}: {self.message[:60]}...)"


@dataclass
class Incident:
    """
    An Incident is created by the Monitoring Agent
    and passed to the Knowledge Agent for investigation.
    """
    service: str
    severity: Severity
    description: str
    incident_id: str = field(default_factory=lambda: f"INC-{str(uuid.uuid4())[:8].upper()}")
    status: IncidentStatus = IncidentStatus.OPEN
    metrics: List[Metric] = field(default_factory=list)
    logs: List[Log] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self):
        return (
            f"Incident(id={self.incident_id}, "
            f"service={self.service}, "
            f"severity={self.severity.value}, "
            f"status={self.status.value})"
        )


@dataclass
class Solution:
    """
    Generated by the Knowledge Agent after RAG investigation.
    Passed to the Self-Healing Agent for execution.
    """
    incident_id: str
    root_cause: str
    healing_prompt: str
    confidence: float
    suggested_commands: List[str] = field(default_factory=list)
    references: List[str] = field(default_factory=list)
    source: str = "knowledge_base"
    created_at: datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"Solution(incident={self.incident_id}, "
            f"confidence={self.confidence:.2f}, "
            f"source={self.source})"
        )


@dataclass
class RemediationAction:
    """
    A single remediation action executed by the Self-Healing Agent.
    """
    incident_id: str
    command: str
    description: str
    action_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    status: RemediationStatus = RemediationStatus.PENDING
    output: Optional[str] = None
    error: Optional[str] = None
    executed_at: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"RemediationAction(id={self.action_id}, "
            f"status={self.status.value}, "
            f"cmd={self.command[:50]})"
        )


@dataclass
class Alert:
    """Sent by the Alerting Agent to notify engineers."""
    incident_id: str
    title: str
    message: str
    severity: Severity
    channel: str
    alert_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    sent: bool = False
    sent_at: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def __str__(self):
        return (
            f"Alert(id={self.alert_id}, "
            f"severity={self.severity.value}, "
            f"channel={self.channel})"
        )


@dataclass
class Deployment:
    """Tracks a deployment triggered by the CI/CD Agent."""
    service: str
    branch: str
    version: str
    deployment_id: str = field(default_factory=lambda: f"DEP-{str(uuid.uuid4())[:8].upper()}")
    status: DeploymentStatus = DeploymentStatus.PENDING
    pipeline_url: Optional[str] = None
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self):
        return (
            f"Deployment(id={self.deployment_id}, "
            f"service={self.service}, "
            f"status={self.status.value})"
        )